# .github/workflows/python-app.yml

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to the correct version

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        make install

    - name: Run the application in the background
      run: |
        make run > server_output.log 2>&1 &
        sleep 10

    - name: Display server output
      run: |
        echo "Server output:"
        cat server_output.log

    - name: Verify server is running
      run: |
        echo "Testing the server..."
        curl --fail http://127.0.0.1:3000 || exit 1

    - name: Success
      run: echo "Server is running successfully."
